//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alicia_En_El_Mundo_Vegano.App_GlobalResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class chien_language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal chien_language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("", typeof(chien_language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        public static string mnuApplicationName {
            get {
                return ResourceManager.GetString("mnuApplicationName", resourceCulture);
            }
        }
        
        public static string mnuContact {
            get {
                return ResourceManager.GetString("mnuContact", resourceCulture);
            }
        }
        
        public static string mnuHome {
            get {
                return ResourceManager.GetString("mnuHome", resourceCulture);
            }
        }
        
        public static string mnuLogin {
            get {
                return ResourceManager.GetString("mnuLogin", resourceCulture);
            }
        }
        
        public static string mnuRegister {
            get {
                return ResourceManager.GetString("mnuRegister", resourceCulture);
            }
        }
        
        public static string myEnglish {
            get {
                return ResourceManager.GetString("myEnglish", resourceCulture);
            }
        }
        
        public static string myVietnamese {
            get {
                return ResourceManager.GetString("myVietnamese", resourceCulture);
            }
        }
    }
}
